source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem "zeus", "~> 0.13.3"
gem "thin", "~> 1.6.0"
gem "pg", "~> 0.17.0"
gem "pry", "~> 0.9.12.2"
gem "rspec-rails", "~> 2.14.0"
gem "font-awesome-rails"
gem "haml", "~> 4.0.3"
gem "zurb-foundation", "~> 4.3.2"
gem 'rails_12factor', group: :production
gem "bourbon", "~> 3.1.8"
gem "gon", "~> 4.1.1"

group :doc do
  gem 'sdoc', require: false
end
