development:
  adapter: postgresql
  encoding: unicode
  database: messages
  pool: 5
  host: localhost
  port: 5432  
   

test:
  adapter: postgresql
  encoding: unicode
  database: messages_dev
  pool: 5
  host: localhost
  port: 5432  
